### ISSUE TITLE
Error en el ejercicio 6 de la relación

### ISSUE THREAD

**Issue by Angeldiaz10** [pedritomelenas/Algebra-Lineal#1]
Profesor creo que hay un error en el enunciado. El punto y el vector director de la recta nos la da en dimensión 2 y el plano está en dimensión 3.

**Comment by pedritomelenas** [comment]
Ángel, gracias. Lo miraré luego, pero los ejercicios no se alojan en este repositorio. Aquí tenemos sólo los guiones.
