### ISSUE TITLE
Error en el guion 5 en apartado de Ecuaciones cartesianas usando las ecuaciones cartesianas del espacio de direcciones

### ISSUE THREAD

**Issue by alejandrofi** [pedritomelenas/Algebra-Lineal#2]
Hay un fallo en este apartado en las ecuaciones implícitas de W ya que pone que A(x1-p1,...,xn-p2)=0 y tendría que ser A(x1-p1,...,xn-pn)=0

**Comment by pedritomelenas** [comment]
@alejandrofi, gracias. Arreglado en https://github.com/pedritomelenas/Algebra-Lineal/commit/5c00e86830638d5d6eb2f26ea1dfd159ac057cbb
