### ISSUE TITLE
Error en el guión del tema 6

### ISSUE THREAD

**Issue by anahj0** [pedritomelenas/Algebra-Lineal#3]
En el apartado de Inversas a izquierda y a derecha de una matriz, en la sexta linea, está escrito $rg(AA^t)$ en vez de $rg(A^t A)$. Gracias

**Comment by pedritomelenas** [comment]
Ana, gracias, aunque sean lo mismo es mejor escribirlo como dices. Arreglado en [de5a9ea](https://github.com/pedritomelenas/Algebra-Lineal/commit/de5a9ea512e816040ff4f7e08a75de89f45be5b2)
